### ISSUE TITLE
S3 file name

### ISSUE THREAD

**Issue by amitdhawan** [embulk/embulk-output-s3#17]
Is it possible to provide the file name of S3 same as the name i take from S3 input plugin for embulk.

My embulk flow is like this -> 

S3 file input ->  Parse file -> S3 file output

So i want to give the same name or format the s3 input file name in s3 output plugin. Can i do this?

**Comment by dmikurube** [comment]
It's impossible by Embulk's nature, not just this plugin, and we have no intention to add a special support for that.
https://github.com/embulk/embulk/issues/1138#issuecomment-480109088
